# Generated by Django 4.2.6 on 2023-10-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='capital',
            field=models.BooleanField(default=False),
        ),
    ]
