version: '3.5'

services:

  app:
    build: .
    ports:
      - "8081:8080"
    volumes:
      - .:/code
    entrypoint: ['sh', 'run-django.sh']
    depends_on:
      - db_prod
    networks:
      - database
      - web


  proxy:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/nginx:/etc/nginx/confi.d/
      - ./log/nginx:/var/log/nginx
      - ./static:/var/www/static
      - ./media:/var/www/media
    networks:
      - web


  db_prod:
    image: mdillon/postgis
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sidia
    ports:
      - "5433:5432"
    volumes:
      - postgres-data-prod:/var/lib/postgresql/data
    networks:
      - database

volumes:
  postgres-data-prod:

networks:
  web:
  database: